# -*- coding: utf-8 -*-
"""input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnqdDM_fBL2Fo3T30IzffHpoPSgtJcP2
"""

from google.colab import drive
drive.mount('/content/drive')
import xarray as xr


def get_user_config() -> str:
    """Yêu cầu người dùng nhập đường dẫn thư mục chứa các tệp NetCDF."""

    default_path = '/content/drive/MyDrive/Group Project 2025/data/'
    print("\n---------------------------------------------------")
    print("  THIẾT LẬP ĐƯỜNG DẪN DỮ LIỆU NETCDF  ")
    print("---------------------------------------------------")

    user_path = input(f" Vui lòng nhập đường dẫn thư mục chứa các tệp NetCDF (Mặc định: {default_path}): ")

    if not user_path:
        user_path = default_path
        print(f"  Không nhập đường dẫn, sử dụng đường dẫn mặc định: {user_path}")

    path_obj = Path(user_path)
    while not path_obj.is_dir():
        if path_obj.is_file():
            print("  Lỗi: Bạn đã nhập TÊN TỆP. Vui lòng nhập đường dẫn THƯ MỤC chứa tệp.")
        else:
            print(f"   Lỗi: Thư mục '{user_path}' không tồn tại. Vui lòng kiểm tra lại.")
        user_path = input(" Vui lòng nhập đường dẫn thư mục hợp lệ: ")
        path_obj = Path(user_path)

    print(f" Đã xác nhận thư mục gốc: {user_path}")
    return str(path_obj)

def load_all_datasets_dynamically():
    """Tự động tìm kiếm, tải tất cả các tệp .nc trong thư mục đã cho."""

    base_path = get_user_config()
    nc_files = glob.glob(os.path.join(base_path, '*.nc'))

    if not nc_files:
        print(" Không tìm thấy tệp NetCDF nào trong thư mục này.")
        return {}

    datasets = {}
    print(f"\n--- Bắt đầu tải {len(nc_files)} tệp NetCDF ---")
    for file_path in nc_files:
        try:
            name = Path(file_path).stem.split('_')[-1]
            ds = xr.open_dataset(file_path)
            datasets[name] = ds
            print(f" Tải thành công '{name}'. Kích thước: {dict(ds.sizes)}")
        except Exception as e:
            print(f" Lỗi khi tải tệp {file_path}: {e}")

    print("\nTổng số tập dữ liệu đã tải:", len(datasets))
    return datasets

def combine_datasets(datasets):
    """Kết hợp các tập dữ liệu đã tải thành một xarray Dataset duy nhất."""
    priority_vars = ['tas', 'tasmax', 'tasmin', 'pr']
    datasets_to_merge = [datasets[name] for name in priority_vars if name in datasets]

    if not datasets_to_merge:
        print(" Không có dữ liệu hợp lệ nào được tìm thấy để kết hợp.")
        return None

    merged = xr.merge(datasets_to_merge, compat='override', join='outer')
    print(f"\n✅ Đã kết hợp dataset. Các biến: {list(merged.data_vars)}")
    return merged

def load_all_data_for_analysis():
    """Thực hiện toàn bộ quy trình gắn kết Drive, tải và kết hợp dữ liệu."""

    drive.mount('/content/drive')
    print(" Đã gắn kết Google Drive.")

    all_datasets = load_all_datasets_dynamically()
    combined_data = combine_datasets(all_datasets)

    return combined_data
